<template>
  <h1>L-Zass price checklist</h1>
  <button :class="{ isSelected: selectedList == 'warframes' }" @click="selectFrame">Warframes</button>
  <button :class="{ isSelected: selectedList == 'weapons' }" @click="selectWeapon">Armes</button>
  <button :class="{ isSelected: selectedList == 'relics' }" @click="selectRelic">Reliques</button>
  <button :class="{ isSelected: selectedList == 'mods' }" @click="selectMod">Mods légendaires</button>
  <button :class="{ isSelected: selectedList == 'arcane' }" @click="selectArcane">Arcanes</button>
  <ProductList :title="'Warframes'" :names="frameNames" :totalNumber="frameNamesTotal.length" v-show="selectedList == 'warframes'" />
  <ProductList :title="'Armes'" :names="weaponsNames" :totalNumber="weaponsNamesTotal.length" v-show="selectedList == 'weapons'" />
  <ProductList :title="'Reliques'" :names="relicsNames" :totalNumber="relicsNamesTotal.length" v-show="selectedList == 'relics'" />
  <ProductList :title="'Mods légendaires'" :names="modsNames" :totalNumber="modsNamesTotal.length" :imgHeight="128" :showEnglish="true" v-show="selectedList == 'mods'" />
  <ProductList :title="'Arcanes'" :names="arcaneNames" :totalNumber="arcaneNamesTotal.length" :showEnglish="true" v-show="selectedList == 'arcane'" />
</template>

<script>
import ProductList from "./components/ProductList.vue";

export default {
  components: { ProductList },
  data() {
    return {
      isLoading: true,
      itemPerRequest: 3,
      delayBetweenRequest: 1500,
      selectedList: "warframes",
      frameNames: [],
      weaponsNames: [],
      modsNames: [],
      relicsNames: [],
      arcaneNames: [],
      frameNamesTotal: [
        "ash_prime_set",
        "atlas_prime_set",
        "banshee_prime_set",
        "chroma_prime_set",
        "ember_prime_set",
        "equinox_prime_set",
        "frost_prime_set",
        "gara_prime_set",
        "hydroid_prime_set",
        "inaros_prime_set",
        "ivara_prime_set",
        "limbo_prime_set",
        "loki_prime_set",
        "mag_prime_set",
        "mesa_prime_set",
        "mirage_prime_set",
        "nekros_prime_set",
        "nezha_prime_set",
        "nova_prime_set",
        "nyx_prime_set",
        "oberon_prime_set",
        "octavia_prime_set",
        "rhino_prime_set",
        "saryn_prime_set",
        "titania_prime_set",
        "trinity_prime_set",
        "valkyr_prime_set",
        "vauban_prime_set",
        "volt_prime_set",
        "wukong_prime_set",
        "zephyr_prime_set",
      ],
      weaponsNamesTotal: [
        "astilla_prime_set",
        "baza_prime_set",
        "boar_prime_set",
        "boltor_prime_set",
        "braton_prime_set",
        "burston_prime_set",
        "cernos_prime_set",
        "corinth_prime_set",
        "latron_prime_set",
        "panthera_prime_set",
        "paris_prime_set",
        "rubico_prime_set",
        "soma_prime_set",
        "stradavar_prime_set",
        "sybaris_prime_set",
        "tenora_prime_set",
        "tiberon_prime_set",
        "tigris_prime_set",
        "vectis_prime_set",
        "zhuge_prime_set",
        "akbolto_prime_set",
        "akbronco_prime_set",
        "akjagara_prime_set",
        "aklex_prime_set",
        "aksomati_prime_set",
        "akstiletto_prime_set",
        "akvasto_prime_set",
        "ballistica_prime_set",
        "bronco_prime_set",
        "euphona_prime_set",
        "hikou_prime_set",
        "lex_prime_set",
        "pandero_prime_set",
        "pyrana_prime_set",
        "sicarus_prime_set",
        "spira_prime_set",
        "vasto_prime_set",
        "zakti_prime_set",
        "ankyros_prime_set",
        "bo_prime_set",
        "dakra_prime_set",
        "destreza_prime_set",
        "dual_kamas_prime_set",
        "fang_prime_set",
        "fragor_prime_set",
        "galatine_prime_set",
        "glaive_prime_set",
        "gram_prime_set",
        "guandao_prime_set",
        "karyst_prime_set",
        "kogake_prime_set",
        "kronen_prime_set",
        "nami_skyla_prime_set",
        "nikana_prime_set",
        "ninkondi_prime_set",
        "orthos_prime_set",
        "pangolin_prime_set",
        "reaper_prime_set",
        "redeemer_prime_set",
        "scindo_prime_set",
        "silva_and_aegis_prime_set",
        "tekko_prime_set",
        "tipedo_prime_set",
        "venka_prime_set",
        "volnus_prime_set",
      ],
      modsNamesTotal: [
        "primed_animal_instinct",
        "primed_bane_of_corpus",
        "primed_bane_of_corrupted",
        "primed_bane_of_grineer",
        "primed_bane_of_infested",
        "primed_charged_shell",
        "primed_chilling_grasp",
        "primed_cleanse_corpus",
        "primed_cleanse_corrupted",
        "primed_cleanse_grineer",
        "primed_cleanse_infested",
        "primed_continuity",
        "primed_cryo_rounds",
        "primed_expel_corpus",
        "primed_expel_corrupted",
        "primed_expel_grineer",
        "primed_expel_infested",
        "primed_fast_hands",
        "primed_fever_strike",
        "primed_firestorm",
        "primed_flow",
        "primed_fulmination",
        "primed_fury",
        "primed_heated_charge",
        "primed_heavy_trauma",
        "primed_morphic_transformer",
        "primed_pack_leader",
        "primed_pistol_ammo_mutation",
        "primed_pistol_gambit",
        "primed_point_blank",
        "primed_pressure_point",
        "primed_quickdraw",
        "primed_ravage",
        "primed_reach",
        "primed_regen",
        "primed_rifle_ammo_mutation",
        "primed_rubedo_lined_barrel",
        "primed_shotgun_ammo_mutation",
        "primed_slip_magazine",
        "primed_smite_corpus",
        "primed_smite_corrupted",
        "primed_smite_grineer",
        "primed_smite_infested",
        "primed_tactical_pump",
        "primed_target_cracker",
      ],
      relicsNamesTotal: [
        "lith_a1_relic",
        "lith_a2_relic",
        "lith_a3_relic",
        "lith_b1_relic",
        "lith_b2_relic",
        "lith_b3_relic",
        "lith_b4_relic",
        "lith_b5_relic",
        "lith_b6_relic",
        "lith_b7_relic",
        "lith_c1_relic",
        "lith_c2_relic",
        "lith_c3_relic",
        "lith_c4_relic",
        "lith_c5_relic",
        "lith_c6_relic",
        "lith_d1_relic",
        "lith_d2_relic",
        "lith_d3_relic",
        "lith_d4_relic",
        "lith_f1_relic",
        "lith_f2_relic",
        "lith_g1_relic",
        "lith_g2_relic",
        "lith_g3_relic",
        "lith_h1_relic",
        "lith_h2_relic",
        "lith_k1_relic",
        "lith_k2_relic",
        "lith_k3_relic",
        "lith_k4_relic",
        "lith_k5_relic",
        "lith_l1_relic",
        "lith_l2_relic",
        "lith_m1_relic",
        "lith_m2_relic",
        "lith_m3_relic",
        "lith_m4_relic",
        "lith_m5_relic",
        "lith_m6_relic",
        "lith_m7_relic",
        "lith_n1_relic",
        "lith_n2_relic",
        "lith_n3_relic",
        "lith_n4_relic",
        "lith_n5_relic",
        "lith_n6_relic",
        "lith_o1_relic",
        "lith_o2_relic",
        "lith_p1_relic",
        "lith_p2_relic",
        "lith_p3_relic",
        "lith_p4_relic",
        "lith_s10_relic",
        "lith_s1_relic",
        "lith_s2_relic",
        "lith_s3_relic",
        "lith_s4_relic",
        "lith_s5_relic",
        "lith_s6_relic",
        "lith_s7_relic",
        "lith_s8_relic",
        "lith_s9_relic",
        "lith_t1_relic",
        "lith_t2_relic",
        "lith_t3_relic",
        "lith_t5_relic",
        "lith_v1_relic",
        "lith_v2_relic",
        "lith_v3_relic",
        "lith_v4_relic",
        "lith_v5_relic",
        "lith_v6_relic",
        "lith_v7_relic",
        "lith_v8_relic",
        "lith_w1_relic",
        "lith_w2_relic",
        "lith_z1_relic",
        "lith_z2_relic",
        "meso_a1_relic",
        "meso_a2_relic",
        "meso_b1_relic",
        "meso_b2_relic",
        "meso_b3_relic",
        "meso_b4_relic",
        "meso_c1_relic",
        "meso_c2_relic",
        "meso_c3_relic",
        "meso_c4_relic",
        "meso_c5_relic",
        "meso_d1_relic",
        "meso_d2_relic",
        "meso_d3_relic",
        "meso_d4_relic",
        "meso_d5_relic",
        "meso_e1_relic",
        "meso_e2_relic",
        "meso_e3_relic",
        "meso_e4_relic",
        "meso_e5_relic",
        "meso_f1_relic",
        "meso_f2_relic",
        "meso_f3_relic",
        "meso_g1_relic",
        "meso_g2_relic",
        "meso_h1_relic",
        "meso_k1_relic",
        "meso_k2_relic",
        "meso_k3_relic",
        "meso_l1_relic",
        "meso_m1_relic",
        "meso_m2_relic",
        "meso_m3_relic",
        "meso_n10_relic",
        "meso_n1_relic",
        "meso_n2_relic",
        "meso_n3_relic",
        "meso_n4_relic",
        "meso_n5_relic",
        "meso_n6_relic",
        "meso_n7_relic",
        "meso_n8_relic",
        "meso_n9_relic",
        "meso_o1_relic",
        "meso_o2_relic",
        "meso_o3_relic",
        "meso_o4_relic",
        "meso_p1_relic",
        "meso_p2_relic",
        "meso_p3_relic",
        "meso_r1_relic",
        "meso_r2_relic",
        "meso_r3_relic",
        "meso_s1_relic",
        "meso_s2_relic",
        "meso_s3_relic",
        "meso_s4_relic",
        "meso_s5_relic",
        "meso_s6_relic",
        "meso_s7_relic",
        "meso_s8_relic",
        "meso_s9_relic",
        "meso_t1_relic",
        "meso_t2_relic",
        "meso_t3_relic",
        "meso_t4_relic",
        "meso_v1_relic",
        "meso_v2_relic",
        "meso_v3_relic",
        "meso_v4_relic",
        "meso_v5_relic",
        "meso_v6_relic",
        "meso_w1_relic",
        "meso_z1_relic",
        "meso_z2_relic",
        "meso_z3_relic",
        "neo_a1_relic",
        "neo_a2_relic",
        "neo_a3_relic",
        "neo_a4_relic",
        "neo_b1_relic",
        "neo_b2_relic",
        "neo_b3_relic",
        "neo_b4_relic",
        "neo_b5_relic",
        "neo_b6_relic",
        "neo_c1_relic",
        "neo_d1_relic",
        "neo_d2_relic",
        "neo_e1_relic",
        "neo_e2_relic",
        "neo_f1_relic",
        "neo_g1_relic",
        "neo_g2_relic",
        "neo_g3_relic",
        "neo_h1_relic",
        "neo_h2_relic",
        "neo_i1_relic",
        "neo_i2_relic",
        "neo_k1_relic",
        "neo_k2_relic",
        "neo_l1_relic",
        "neo_m1_relic",
        "neo_m2_relic",
        "neo_m3_relic",
        "neo_n10_relic",
        "neo_n11_relic",
        "neo_n12_relic",
        "neo_n13_relic",
        "neo_n14_relic",
        "neo_n1_relic",
        "neo_n2_relic",
        "neo_n3_relic",
        "neo_n4_relic",
        "neo_n5_relic",
        "neo_n6_relic",
        "neo_n7_relic",
        "neo_n8_relic",
        "neo_n9_relic",
        "neo_p1_relic",
        "neo_r1_relic",
        "neo_r2_relic",
        "neo_r3_relic",
        "neo_r4_relic",
        "neo_s10_relic",
        "neo_s11_relic",
        "neo_s12_relic",
        "neo_s13_relic",
        "neo_s14_relic",
        "neo_s1_relic",
        "neo_s2_relic",
        "neo_s3_relic",
        "neo_s5_relic",
        "neo_s6_relic",
        "neo_s7_relic",
        "neo_s8_relic",
        "neo_s9_relic",
        "neo_t1_relic",
        "neo_t2_relic",
        "neo_t3_relic",
        "neo_v1_relic",
        "neo_v2_relic",
        "neo_v3_relic",
        "neo_v4_relic",
        "neo_v5_relic",
        "neo_v6_relic",
        "neo_v7_relic",
        "neo_v8_relic",
        "neo_z1_relic",
        "neo_z2_relic",
        "neo_z3_relic",
        "neo_z4_relic",
        "neo_z5_relic",
        "neo_z6_relic",
        "neo_z7_relic",
        "axi_a10_relic",
        "axi_a11_relic",
        "axi_a12_relic",
        "axi_a1_relic",
        "axi_a3_relic",
        "axi_a4_relic",
        "axi_a6_relic",
        "axi_a7_relic",
        "axi_a8_relic",
        "axi_a9_relic",
        "axi_b1_relic",
        "axi_b2_relic",
        "axi_b3_relic",
        "axi_b4_relic",
        "axi_c1_relic",
        "axi_c2_relic",
        "axi_c3_relic",
        "axi_c4_relic",
        "axi_c5_relic",
        "axi_d1_relic",
        "axi_d2_relic",
        "axi_e1_relic",
        "axi_e2_relic",
        "axi_g1_relic",
        "axi_g2_relic",
        "axi_g3_relic",
        "axi_g4_relic",
        "axi_h1_relic",
        "axi_h2_relic",
        "axi_h3_relic",
        "axi_h4_relic",
        "axi_h5_relic",
        "axi_k1_relic",
        "axi_k2_relic",
        "axi_k3_relic",
        "axi_k4_relic",
        "axi_k5_relic",
        "axi_l1_relic",
        "axi_l2_relic",
        "axi_l3_relic",
        "axi_l4_relic",
        "axi_l5_relic",
        "axi_m1_relic",
        "axi_n1_relic",
        "axi_n2_relic",
        "axi_n3_relic",
        "axi_n4_relic",
        "axi_n5_relic",
        "axi_n6_relic",
        "axi_o1_relic",
        "axi_o2_relic",
        "axi_o3_relic",
        "axi_o4_relic",
        "axi_p1_relic",
        "axi_p2_relic",
        "axi_p3_relic",
        "axi_r1_relic",
        "axi_r2_relic",
        "axi_r3_relic",
        "axi_s1_relic",
        "axi_s2_relic",
        "axi_s3_relic",
        "axi_s4_relic",
        "axi_s5_relic",
        "axi_s6_relic",
        "axi_s7_relic",
        "axi_t1_relic",
        "axi_t2_relic",
        "axi_t3_relic",
        "axi_t4_relic",
        "axi_t5_relic",
        "axi_t6_relic",
        "axi_v1_relic",
        "axi_v2_relic",
        "axi_v3_relic",
        "axi_v4_relic",
        "axi_v5_relic",
        "axi_v6_relic",
        "axi_v7_relic",
        "axi_v9_relic",
        "axi_w1_relic",
        "axi_w2_relic",
        "axi_z1_relic",
      ],
      arcaneNamesTotal: [
        "arcane_acceleration",
        "arcane_aegis",
        "arcane_agility",
        "arcane_arachne",
        "arcane_avenger",
        "arcane_awakening",
        "arcane_barrier",
        "arcane_blade_charger",
        "arcane_bodyguard",
        "arcane_consequence",
        "arcane_deflection",
        "arcane_energize",
        "arcane_eruption",
        "arcane_fury",
        "arcane_grace",
        "arcane_guardian",
        "arcane_healing",
        "arcane_ice",
        "arcane_momentum",
        "arcane_nullifier",
        "arcane_phantasm",
        "arcane_pistoleer",
        "arcane_precision",
        "arcane_primary_charger",
        "arcane_pulse",
        "arcane_rage",
        "arcane_resistance",
        "arcane_strike",
        "theorem_contagion",
        "theorem_demulcent",
        "theorem_infection",
        "arcane_tanker",
        "arcane_tempo",
        "arcane_trickery",
        "arcane_ultimatum",
        "arcane_velocity",
        "arcane_victory",
        "arcane_warmth",
        "magus_vigor",
        "magus_husk",
        "magus_cadence",
        "magus_cloud",
        "magus_replenish",
        "magus_elevate",
        "magus_nourish",
        "magus_overload",
        "magus_glitch",
        "magus_revert",
        "magus_firewall",
        "magus_drive",
        "magus_lockdown",
        "magus_destruct",
        "magus_anomaly",
        "magus_melt",
        "magus_accelerant",
        "magus_repair",
        "virtuos_null",
        "virtuos_tempo",
        "virtuos_fury",
        "virtuos_strike",
        "virtuos_shadow",
        "virtuos_ghost",
        "virtuos_trojan",
        "virtuos_surge",
        "virtuos_spike",
        "virtuos_forge",
        "exodia_brave",
        "exodia_force",
        "exodia_hunt",
        "exodia_might",
        "exodia_triumph",
        "exodia_valor",
        "exodia_contagion",
        "exodia_epidemic",
        "pax_bolt",
        "pax_charge",
        "pax_seeker",
        "pax_soar",
        "residual_boils",
        "residual_malodor",
        "residual_shock",
        "residual_viremia",
      ],
    };
  },
  methods: {
    /** Because to much request at the same time doesn't work */
    addItem(list, totalList, callback) {
      if (list.length < totalList.length) {
        list = list.concat(totalList.slice(list.length, Math.min(totalList.length, list.length + this.itemPerRequest)));
      }
      if (list.length < totalList.length) {
        setTimeout(() => callback(), 1); //Because we need to return
      } else {
        this.isLoading = false;
      }
      return list;
    },
    requestFrame() {
      if (this.selectedList == "warframes")
        setTimeout(() => (this.frameNames = this.addItem(this.frameNames, this.frameNamesTotal, this.requestFrame)), this.delayBetweenRequest);
    },
    requestWeapon() {
      if (this.selectedList == "weapons")
        setTimeout(() => (this.weaponsNames = this.addItem(this.weaponsNames, this.weaponsNamesTotal, this.requestWeapon)), this.delayBetweenRequest);
    },
    requestRelic() {
      if (this.selectedList == "relics")
        setTimeout(() => (this.relicsNames = this.addItem(this.relicsNames, this.relicsNamesTotal, this.requestRelic)), this.delayBetweenRequest);
    },
    requestMod() {
      if (this.selectedList == "mods")
        setTimeout(() => (this.modsNames = this.addItem(this.modsNames, this.modsNamesTotal, this.requestMod)), this.delayBetweenRequest);
    },
    requestArcane() {
      if (this.selectedList == "arcane")
        setTimeout(() => (this.arcaneNames = this.addItem(this.arcaneNames, this.arcaneNamesTotal, this.requestArcane)), this.delayBetweenRequest);
    },
    selectFrame() {
      this.selectedList = "warframes";
      this.requestFrame();
    },
    selectWeapon() {
      this.selectedList = "weapons";
      this.requestWeapon();
    },
    selectRelic() {
      this.selectedList = "relics";
      this.requestRelic();
    },
    selectMod() {
      this.selectedList = "mods";
      this.requestMod();
    },
    selectArcane() {
      this.selectedList = "arcane";
      this.requestArcane();
    },
  },
  mounted() {
    this.requestFrame();
  },
};
</script>

<style lang="css">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

#app > button {
  margin: 3px;
  border: none;
  padding: 15px 30px;
  font-size: 16px;
  color: white;
  background-color: #538bc1;
}

#app > button.isSelected {
  color: black;
  background-color: #e3ecf5;
}
</style>
